#!/usr/bin/env python3

# git regret - Allows you to delete changes to a GIT repository.
# Copyright (C) 2015  Niklas Sombert
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from argparse import ArgumentParser

#parse the arguments
parser = ArgumentParser(prog="git regret", description="Delete changes in your repository because you deeply regret them.")
group = parser.add_mutually_exclusive_group()
group.add_argument("--soft", help="Delete all changes since the last commit.", action="store_true")
group.add_argument("--hard", help="Delete the last commit.", action="store_true")
args = parser.parse_args()

if args.soft:
    pass
elif args.hard:
    pass
else:
    print("How deeply do you regret your changes? See 'git regret -h' for help.")
